sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness
sonar.host.url=http://localhost:9000
sonar.login=sqp_d95454650272ed38a4e1ace86bfa82ba959a6d5f

sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8