apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest
      version: v1
  template:
    metadata:
      labels:
        app: aceest
        version: v1
    spec:
      containers:
      - name: aceest-container
        image: vighneshdevane/aceest-fitness:latest
        ports:
        - containerPort: 5000