apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-v4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest
      version: v4
  template:
    metadata:
      labels:
        app: aceest
        version: v4
    spec:
      containers:
      - name: aceest-container
        image: vighneshdevane/aceest-fitness:v4
        ports:
        - containerPort: 5000