apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
  template:
    metadata:
      labels:
        app: aceest
    spec:
      containers:
      - name: aceest-container
        image: vighneshdevane/aceest-fitness:latest
        ports:
        - containerPort: 5000