apiVersion: v1
kind: Service
metadata:
  name: aceest-service
spec:
  type: NodePort
  selector:
    app: aceest
    version: green
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007